name: PhishingEmailDetectionSystem

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/master.yml'

jobs:
  build-and-deploy:
    name: Build and Deploy All Services
    environment: staging
    runs-on: [phishingemaildetectionsystem]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Stop old containers and keep volumes & cache
        run: docker compose down --remove-orphans

      - name: Build and Deploy with Docker Compose
        run: docker compose up -d --build
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
          VT_API_KEY: ${{ secrets.VT_API_KEY }}